# render.yaml
services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      "apt-get update"
      "apt-get install -y ffmpeg"
      "pip install -r requirements.txt"
    startCommand: "uvicorn rtspbackend.asgi:application --port 8080"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rtspbackend.settings
      - key: PYTHON_VERSION
        value: 3.10
