# Generated by Django 4.2.21 on 2025-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
